### ISSUE TITLE
About ceres-solver threading

### ISSUE THREAD

**Issue by fuenwang** [mapillary/OpenSfM#102]
Hi:
I found one thing strange that no matter how I set "processes" in config.yaml, bundle adjustment won's run with multithread. But in the [Dockfile](https://github.com/mapillary/OpenSfM/blob/master/Dockerfile),   
I found 
cmake .. -DCMAKE_C_FLAGS=-fPIC -DCMAKE_CXX_FLAGS=-fPIC -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DOPENMP=OFF when build ceres-solver. After I remove -DOPENMP=OFF, bundle adjustment strarts run in multithread. Is this parameter set for some reason?

**Comment by paulinus** [comment]
Depending on where you run the code, you might want multi-threading or not. We disable multi-threading because we run the code on machines that are doing other tasks simultaneously and we don't want each of the task to use multiple threads.
In your case, as you have seen, you should not disable OpenMP.  Are you using the Dockerfile to build and run OpenSfM?  Note that we included a Dockerfile just as an example and to use it in Travis. Feel free to use your own version of it.

**Comment by andreasg123** [comment]
I was about to comment on the same issue.  Turning OpenMP on does not seem to have negative consequences on a dedicated system and speeds up processing.  On a system with 16 cores, `top` shows around 1200% CPU usage when OpenMP is turned on.  That doesn't quite use all cores but is still much faster.

**Comment by fuenwang** [comment]
@andreasg123 I have the same problem, cere-solver seems not to use all the resource to run BA. I don't know if there other way to speed up bundle adjustment.

**Comment by andreasg123** [comment]
@fuenwang It's not always possible to use all cores.  Ceres Solver seems to rely mostly on OpenMP.  That can only parallelize loops where loop iterations are fairly independent of each other.  All code in between those loops still runs in a single thread.

I briefly looked at the reconstruction code and I didn't see any good alternatives for computing something in parallel.  Also, it's not a good idea to combine multithreading or multiprocessing with OpenMP because one can't really control how many CPU cores would be used in total.

To me, keeping 12 cores busy on average is a big win over using just one core.

You can have a look at #104 that makes the initialization step for the bundle adjustment more parallel.

**Comment by paulinus** [comment]
I've removed the `-DOPENMP=OFF` from the Dockerfile so that it does not suggest that it should be used.  (Also moved the mostly static part of the Dockerfile to https://github.com/paulinus/opensfm-docker-base so that test builds are faster)

As for computing parts of the reconstruction in parallel. The current implementation does an incremental reconstruction. Because it is incremental it is hard to find thing to run in parallel. For large reconstructions, the bottleneck should be bundle adjustment so internal Ceres parallelism is the best bet.
