### ISSUE TITLE
opensfm/bin/opensfm undistort added additional `jpg' to filenames

### ISSUE THREAD

**Issue by luckyapr** [mapillary/OpenSfM#120]
When called, the undistorted images will be saved to `opensfm/undistorted/` folder with additional `jpg`, i.e. `image.jpg` will be saved as `image.jpg.jpg`.

References in NVM file using the original filenames though. Without extra `jpg` in them. 

Easily fixed with the following:
```
diff -Naur opensfm-orig/opensfm/dataset.py opensfm/opensfm/dataset.py
--- opensfm-orig/opensfm/dataset.py     2016-12-11 22:34:24.481225042 -0700
+++ opensfm/opensfm/dataset.py  2016-12-11 22:35:09.050039193 -0700
@@ -69,7 +69,7 @@

     def _undistorted_image_file(self, image):
         """Path of undistorted version of an image."""
-        return os.path.join(self._undistorted_image_path(), image + '.jpg')
+        return os.path.join(self._undistorted_image_path(), image)

     def undistorted_image_as_array(self, image):
         """Undistorted image pixels as 3-dimensional numpy array (R G B order)"""
```

**Comment by paulinus** [comment]
I've added the extra `.jpg` because the original images might not be JPEG files.  What is NVM here?

**Comment by luckyapr** [comment]
hmm, I guess then there shall be a check whether the image has the extension already or not. 

NVM file is one generated by `opensfm export_visualsfm`.

**Comment by paulinus** [comment]
I see the problem now. Thanks for the details.

Conditionally adding the `.jpg` would work, but always adding it seems simpler to handle.

In any case, the problem with NVM is better solved by using the name from dataset rather than relying on that name to have a certain shape.

I've updated the `export_visualsfm` to do so https://github.com/mapillary/OpenSfM/commit/f80abbcb09a0ec6b016b967f291aa09f6567c39f

Please let me know if that solve your problem, thanks!

**Comment by luckyapr** [comment]
Though it looks weird with `.jpg.jpg` in the end, but it does the job. Thanks a lot!
