### ISSUE TITLE
Output produced in reconstruction.json

### ISSUE THREAD

**Issue by kevin-george** [mapillary/OpenSfM#121]
Once we run the bin/run_all on the dataset, are the rotation values specified in the reconstruction.json euler angles? Can anyone confirm this?

**Comment by paulinus** [comment]
The rotation values are in angle/axis format.  You can convert it to a rotation matrix like this https://github.com/mapillary/OpenSfM/blob/f80abbcb09a0ec6b016b967f291aa09f6567c39f/opensfm/types.py#L50-L52

**Comment by garlac** [comment]
Hi All,
New to this discipline. Need some help.

I am having a use case where I require angles to rotate world coordinate points(X,Y,Z) in order to align with image coordinate system..

I saw some values under rotation:[... ] in reconstruction.json for each camera, but not sure how to use these?

Are these values similar to yaw, pitch, roll?..or Do I need rotation matrix to solve my use case?

Thank you.
