### ISSUE TITLE
types.py name collision

### ISSUE THREAD

**Issue by mattbrown11** [mapillary/OpenSfM#142]
I was having some trouble with types.py colliding with the built-in types.  In features.py, it imports csfm directly.  Therefore, I thought I had to add .../OpenSfM/build/lib/opensfm to my PYTHONPATH.  However, types.py is in that directory, which cases a collision with the built-in version.  To solve the issue, I moved cfsm.so to a different directory by itself and then added that directory to my PYTHONPATH.

Not sure whether there was something weird about my environment that lead to this state.

**Comment by paulinus** [comment]
You should set the `PYTHONPATH` to `../OpenSfM` or to `../OpenSfM/build/lib` without the trailing `opensfm`

That should prevent the collision.

Note that when built, `csfm.so` is copied to `../OpenSfM/opensfm`. So no need to use the build folder.

Otherwise, yes `types.py` is a name that we might want to change.
