### ISSUE TITLE
Can this method find out camera position in the situation when I took pictures going upstairs?

### ISSUE THREAD

**Issue by Dorothy-2016** [mapillary/OpenSfM#164]
Thanks for your OpenSfM method ,i can find camera position in most situations indoors and outdoors,but there is a situation that when i took photos going upstairs,then use this method to find camera position,but it is always wrong,i try to find the reason but have not  had a result yet,can you give me some advice?Thank you very much!

**Comment by paulinus** [comment]
What is the wrong with the result you get? is the reconstruction empty, or deformed, or tilted? Could you share the dataset?

Going upstairs is not a problem. The only expected inconvenience is that the model might end up tilted since the final alignment step assumes you move on the ground to guess the gravity direction. 

If you get empty or deformed reconstructions, the most likely reason is that matching is not finding enough correspondences between shots.

**Comment by YanNoun** [comment]
No answer for a while, closing.
