### ISSUE TITLE
Run on berlin example is non-deterministic

### ISSUE THREAD

**Issue by shooshx** [mapillary/OpenSfM#213]
Running the complete pipeline (opensfm_run_all) on the berlin example twice outputs slightly different results.
it seems that everything is the same except the final reconstruction.json which has slightly different rotations and translations for shots and points.
What is the source of this non-determinism?

**Comment by erikreed** [comment]
I'm aware of a few sources of randomness.:
- Feature matching via RANSAC. In OpenSFM the relevant section is here: https://github.com/mapillary/OpenSfM/blob/8097631c090679c8ed64b083c844b76ab357a0a6/opensfm/matching.py#L82
- Initial two view reconstruction (i.e. Nister's Five Point algorithm) uses RANSAC: https://github.com/mapillary/OpenSfM/blob/8097631c090679c8ed64b083c844b76ab357a0a6/opensfm/reconstruction.py#L450
- Probably a minimal effect, but worth considering is that the Ceres solver (i.e. bundle adjustment) is non-deterministic with threading enabled: https://groups.google.com/forum/#!topic/ceres-solver/F_bbG_5afnY

Lastly, computing the depthmaps with PatchMatch (the default) would yield different point clouds (but not the rotation/translation deltas you're seeing).

**Comment by shooshx** [comment]
1. the matches I see in both runs are the same so it's not that
2. I'll check the two views selected to see if that's it
3. This thread says ceres is non-deterministic only if you set options.linear_solver_threads > 1, which you don't. reconstruction.py only sets options.num_threads. Is there a reason not to set options.linear_solver_threads to >1 as well?
4. I'm not running depth maps at all.

**Comment by erikreed** [comment]
While I doubt any major difference is due to Ceres, but if you're using the Berlin example without modifying processes in the config.yaml, you're indeed using 8 threads.

Defined here:
https://github.com/mapillary/OpenSfM/blob/8097631c090679c8ed64b083c844b76ab357a0a6/data/berlin/config.yaml#L5

Set here:
https://github.com/mapillary/OpenSfM/blob/8097631c090679c8ed64b083c844b76ab357a0a6/opensfm/reconstruction.py#L93

Used here:
https://github.com/mapillary/OpenSfM/blob/8097631c090679c8ed64b083c844b76ab357a0a6/opensfm/src/bundle.h#L1075-L1076

**Comment by shooshx** [comment]
Ah, thank you!

**Comment by YanNoun** [comment]
@erikreed @shooshx I confirm that the combination of RANSACs + Ceres is the root cause of non-deterministic behaviour. Results should be identical up to some epsilon however.
