### ISSUE TITLE
How to use OpenSfM viewer to watch 360 degree panorama photos

### ISSUE THREAD

**Issue by AaronQi0731** [mapillary/OpenSfM#235]
I would like to know how to use OpenSfM viewer to watch 360 degree panorama photos. like Google street map, I can look around, not only go forward and backward. I made the structure with equirectangular type photo. Many thx.

**Comment by AaronQi0731** [comment]
look around means I can stand in a position and look the thing around me. in other words, rotating in a position. this

**Comment by AaronQi0731** [comment]
look around means I can stand in a position and look the thing around me. in other words, rotating in a position. many thanks.

**Comment by paulinus** [comment]
You can use SHIFT+DRAG to look around.

What you won't be able to do is to easily move from one image to another using the arrows on the screen. This is because those arrows were designed for perspective images that have a determined viewing direction. For panoramas, one should ignore that direction.

It is possible to modify the code in `reconstruction.html` to enable better navigation for panoramas. If you get to do it, please let us know. Thanks!

**Comment by AaronQi0731** [comment]
Thanks Pau. Yes, I would like do navigation for panoramas in OpenSfM, Like google street map. could you give me some support?

**Comment by paulinus** [comment]
The code computing the possible motions is [here](https://github.com/mapillary/OpenSfM/blob/b05ccbe75f74b16e1ad05eb1ae32f38188843a62/viewer/reconstruction.html#L1093-L1168).  It checks whether there are images that would produce the `wantedMotion` and that look towards the `wantedDirs`. 

It needs to be modified so that, in case the images are 360, the `wantedDirs` are ignored.
