### ISSUE TITLE
What convention is used to geotag the example imagery?

### ISSUE THREAD

**Issue by angussmitchell** [mapillary/OpenSfM#278]
I'm having issues with providing the GPS location of images within the exif fields of images. I used the same convention as specified in the script https://github.com/mapillary/OpenSfM/blob/master/bin/update_geotag where GPS information written to each image as follows:

>  metadata["Exif.GPSInfo.GPSLatitude"] = exiv_lat
    metadata["Exif.GPSInfo.GPSLatitudeRef"] = lat_deg[3]
    metadata["Exif.GPSInfo.GPSLongitude"] = exiv_lon
    metadata["Exif.GPSInfo.GPSLongitudeRef"] = lon_deg[3]
    metadata["Exif.Image.GPSTag"] = 654
    metadata["Exif.GPSInfo.GPSMapDatum"] = "WGS-84"
    metadata["Exif.GPSInfo.GPSVersionID"] = '2 0 0 0'
    metadata["Exif.GPSInfo.GPSImgDirection"] = exiv_bearing
    metadata["Exif.GPSInfo.GPSImgDirectionRef"] = "T"

This seems to geotag the images, with the information visible in the exif folder after running extract_metadata. After testing on my own datasets, it seems that these geotags are being ignored. 

My concern, is that this method seems to be different to that provided in the example data - for example the berlin dataset contains GPS information in the image description field:

![image](https://user-images.githubusercontent.com/22647548/35539600-68fb44a8-05a6-11e8-845f-17f92322bf03.png)

My final question would be this: how was the GPS and heading information input to the example data? Was the data added manually by the opensfm team, or was it added automatically by the camera? If it was added using a script, can we have access to it? 

Thanks alot!

**Comment by paulinus** [comment]
I'm not sure I understand what you want to do. Do you want to add GPS values to the EXIF in the images before running OpenSfM or after?

The update_geotag script will write the GPS positions obtained after running OpenSfM back to the original image. This is a rare need and you should probably not need to do that.

Otherwise, the information in the `ImageDescription` tag is used by Mapillary to write additional info to the images that are uploaded to mapillary.com. OpenSfM does not use this information at all. It does only use the standard EXIF tags.

**Comment by angussmitchell** [comment]
Thanks @paulinus,  this answers my question - mainly I was concerned that I needed to be using the image description field to provide geotags (as is seen in the berlin and lund datasets). I see now that I can just copy the method used in "update_geotag" if I want to geotag images before running the OpenSfM pipeline.
