### ISSUE TITLE
[Question] Merging of depth map to produce point cloud[Solved]

### ISSUE THREAD

**Issue by ManishSahu53** [mapillary/OpenSfM#295]
I have a large dataset of ~1775 images, 24MP each. I could generate individual depth map, cleaning and pruning of depth map. But when process comes to merging of depth map to produce point cloud, it consumes all of my memory(32 GB Ram, 18 Swap). Can you tell how to merge depth map of large datasets without having memory issue?
Thanks

**Comment by ManishSahu53** [comment]
solved.
Added a condition statement 

    points = []
    normals = []
    colors = []
    count = 0
    clusters = 0;
    length_shots_ids = len(shot_ids)
    im_per_cluster = 350  # for 32 GB Ram PC
    no_cluster_points = length_shots_ids/im_per_cluster + 1

if count>im_per_cluster:
		clusters  = clusters + 1;
		count = 0;
		points = np.concatenate(points)
		normals = np.concatenate(normals)
		colors = np.concatenate(colors)
	    	ply = point_cloud_to_ply(points, normals, colors)
		print 'saving cluster ' +str(clusters)
    		with io.open_wt(data._depthmap_path() + '/'+str(clusters)+'_merged.ply') as fout:
    			fout.write(ply)
		points =[]
		normals = []
		colors= []

**Comment by ManishSahu53** [comment]
@paulinus please review this. If found appropriate then kindly add this in opensfm as this would be useful for merging point cloud of memory greater than running PC has.

**Comment by paulinus** [comment]
@ManishSahu53, it is great that you could handle this file size by splitting the output. I think that including this as default is tricky since properly handling the splitting depends on many factors. Since it is only the final merge that requires too much ram, you can do it in a separate script the way you need it. Thanks for sharing the solution.

**Comment by ManishSahu53** [comment]
Can you tell what are other factors?

**Comment by paulinus** [comment]
I was thinking that finding the size of the clusters that can fit into memory can be difficult since the size of the point cloud for each depthmap will change for each dataset.

Also, we would want each cluster to contain images that are related which will require a clustering algorithm.

In all, I think it is better to optimize the code so that there is less need to split the point cloud. We are only concatenating the results and that should not be that expensive.

In this regard, we have improved the memory consumption of this part by quite a lot recently, on a branch https://github.com/mapillary/OpenSfM/commit/a0f6081f1769691b45af82d1ed7b50a3f84d9a09  It turned out that generating the text of the ply was the most memory hungry step and easy to do iteratively.

I'll look into getting this improvement to the master branch.

**Comment by paulinus** [comment]
the improvement is now on master
