### ISSUE TITLE
It able to Compute GPS coordinates

### ISSUE THREAD

**Issue by AaronQi0731** [mapillary/OpenSfM#301]
Hi, May I ask a question about that, if I was tag a image with gps coordinates, and the OpenSfM can help me to compute other images gps information?

**Comment by paulinus** [comment]
Hi @AaronQi0731,

OpenSfM builds a reconstruction by finding the relative position between images. It then aligns the reconstruction to the GPS data available. When only some images have GPS data, it will still align the entire reconstruction to that data, so you will get the aligned positions for the images without GPS too.

To get the reconstructed camera positions into a text file you can use the `export_geocoords` command. For example to get the UTM coords of the berlin dataset you would run
```
bin/opensfm export_geocoords  --proj="+proj=utm +zone=56 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs" --image-positions  data/berlin
```
which will write the coordenates in the file `data/berlin/image_geocoords.tsv`

**Comment by AaronQi0731** [comment]
If I just tag one image or two images with gps information. When I finished reconstruction (succeed), the OpenSfM still can help me to compute other images's gps? e.g. There are 50 iamges in a dataset, and I was tag the gps position information for one or two in them, and when OpenSfM successful reconstruct the structure, Can we get the position information of other images? in other words, It is able to return other images' gps information via OpenSfM computed? Many thanks.

**Comment by paulinus** [comment]
Yes, you will get the position of all of the reconstructed images including the ones that did not have GPS originally. It is better if you geotag at least 3 images.

**Comment by GITNE** [comment]
@paulinus Does this also work on the Mapillary pipeline currently in production? To test this, I have deliberately *deleted* the GPS tags from some images in a sequence and uploaded them. Images lacking GPS meta data simply popped up at 0.0 N 0.0 E. So, this sort of disproves your claim.

I have not tested this feature locally yet.

**Comment by GITNE** [comment]
Does this feature require GCPs? If so, my next question would be if a protocol exists to pass GCPs in images uploaded to Mapillary? Perhaps in the—already heavily abused EXIF tag—`ImageDescription` JSON object?

**Comment by paulinus** [comment]
@GITNE, images missing GPS tags are ignored in mapillary. Without GPS, it is not possible for us to know where in the world the image was taken and which neighboring images should be used to refine the position.
In the context of OpenSfM, you provide a reduced set of images which are taken in the same area. It is then possible to align those images with each other without using GPS information.

On the second question, there is no way to provide GCP to Mapillary.

**Comment by GITNE** [comment]
> @GITNE, images missing GPS tags are ignored in mapillary. Without GPS, it is not possible for us to know where in the world the image was taken and which neighboring images should be used to refine the position.

I am not convinced that we are completely out of luck, since Mapillary sequences are grouped by `MAPSequenceUUID`s and/or *ElasticSearch* sequence keys. Hence, we already know which images we should try to match them against (assuming that at least one image in the sequence has proper GPS data). Now, there would be two ways to try to match the bare image (without GPS data) to the rest of the sequence.

1. Position the image between the previous and next image in the sequence based on time stamps (maybe including distance compensation based on time) or if only one image has GPS data just position it close to that.

if that fails we can still…

2. Try to match the bare image to every image with GPS data **in** **the** **sequence**

Finally, we would export the reconstructed position to the bare image (or only to the meta data database in order to save the original).

Sure, in order to be able to position any random image without GPS data would require matching to every image on Mapillary, which of course would command an unacceptable amount of computational effort. Though, deep learning could help reduce the computational cost significantly here. But, we are not talking about this class of images (yet).

> On the second question, there is no way to provide GCP to Mapillary.

Alright, I think, I came up with something today. :wink:

**Comment by moopene36607** [comment]
You may find the answer there.
https://github.com/mapillary/OpenSfM/issues/301

**Comment by YanNoun** [comment]
No answer in a while, closing.
