### ISSUE TITLE
Incorporate camera extrinsics into initialisation, reproduction errors, BA two runs

### ISSUE THREAD

**Issue by russkel** [mapillary/OpenSfM#317]
Hi Pau, I am modifying/extending OpenSfM for a project and was hoping you could answer some questions:

1) How can I incorporate extrinsic camera details into the initalisation of the reconstruction? We have a number of cameras where we know the translations and rotations relative to one camera due to calibration. We want SfM to use these values as a prior.

2) How to trim out sparse points with large reproduction errors? When viewing the sparse reconstruction using the viewer, there are some points that lie quite far away from the scene that is being reconstructed. 

3) Why is bundle run twice in this function?
https://github.com/mapillary/OpenSfM/blob/ad0eacddfc85283e78abaa90732486a76d35dfa7/opensfm/reconstruction.py#L730

Thanks for your help,

Russ

**Comment by russkel** [comment]
Another question:

In this comment here https://github.com/mapillary/OpenSfM/issues/84#issuecomment-233473956 you mention the focal parameter is the ratio between the focal length and sensor size. However the ratio is passed directly into the get_K() function as seen here:

https://github.com/mapillary/OpenSfM/blob/ee88dd1b4b422daf64913ff2f0512d84843c571c/opensfm/types.py#L272

This is then passed into the openCV undistort function as the camera matrix. Is this correct or should it be multiplied by width and height of the image?

**Comment by paulinus** [comment]
Hi @russkel,
answering following the numbers:

1. The first goal of OpenSfM is to find the camera positions and build a reconstruction.json. If you already have them, then you can build a reconstruction.json (or a types.Reconstruction object) on your own. Depending on the precision of it, you might want to refine it using bundle adjustment. See a comment about how to do so [here](https://github.com/mapillary/OpenSfM/issues/129#issuecomment-274278054).  And then you can run the dense reconstruction if that is what you are looking for.

2. I wonder too. SfM methods (not only opensfm) tend to generate some erroneous points that lie at random places. The main source of those are mismatches usually from repetitive structures. That is, matching thinks that a point in one image corresponds to a certain point in another image. That turns to be wrong and then when we triangulate the point we finding in some random location. Many of those errors are removed by the geometric verifications in RANSAC and the pruning of high reprojection points after bundle. Unfortunately, some mismatches still pass those tests.  One way to get fewer of those is to require at least 3 points per track with the option `min_track_length: 2`. This adds redundancy to the triangulation and increases the chances of the tests detecting a mismatch.

3. We bundle after each triangulation step to adjust the placements of the point and the cameras. We triangulate twice because after the first bundle, things move and we may be able to triangulate more points. Ideally, we would bundle and triangulate for a while until convergence. Doing it 2 times is a random compromise. Doing 1 times would be faster and less precise. Doing 3 times would be slower and more precise.

4. Opensfm normalizes the coordinates of the points. `get_K` returns the `K` matrix associated with this normalized coordinates. Depending on whether you work with normalized coordinates or standard pixel coordinates you will need `get_K` or `get_K_pixel_coordinates`. In places like [here](https://github.com/mapillary/OpenSfM/blob/master/opensfm/types.py#L241) we work with normalized coordinates so we use `get_K`

I hope this still helps
