### ISSUE TITLE
OpenSfM creates double image at right-angles from pictures of head.

### ISSUE THREAD

**Issue by nigelkeirross** [mapillary/OpenSfM#320]
I have been using opensfm to create a 3d image from multiple (about 150) photyographs taken of someones head. The idea is to create a 3d point cloud, then use meshlab to create a mesh, and 3d print the head.
I have been doing this with reasonable success, but the latest person generates 2 distinct models of the head. There is a main one in normal position, but there is also a second one created that intersects with the first, and seems to be at right angles, in one case, or as in the attachment, rotated & behind the other head, at a slight angle. Can you suggest what might be happening?
![doublerob](https://user-images.githubusercontent.com/21008320/39528724-cac9987e-4e1c-11e8-9b48-7709c29bef7e.png)

**Comment by paulinus** [comment]
It seems like during the reconstruction, one image got wrongly positioned and then the reconstruction grows around it. This is one of the handicaps of incremental reconstructions where it is hard to recover from an error.

It is likely that the misalignment is caused by the repetitive texture of the shirt. Since there are a lot of similar circles, it may happen that the reconstruction aligned the wrong circles together.

If you can capture with a different shirt, I would give it a try. Otherwise, if you need to reuse these images, then you can try masking out the shirt.

**Comment by nigelkeirross** [comment]
I have finally managed to "edit" the shirts out of the 200 photos, replacing with white (using logistic regression), and all is working as it should be. Many thanks!

**Comment by paulinus** [comment]
Happy to hear! thanks for persisting
