### ISSUE TITLE
Testing with a set of images. Not sure about result.

### ISSUE THREAD

**Issue by michaelgli** [mapillary/OpenSfM#35]
I'm testing with 5 images of a mouse:
Here is the result picture: I'm hoping to see the shape of the mouse. I'm using the same config.yaml as the berlin dataset. Should I change the config.yaml to get a better result? Thanks, -michael

![screen shot 2015-05-23 at 5 42 30 pm](https://cloud.githubusercontent.com/assets/12475528/7785980/ff2f258c-0173-11e5-8180-d2f93abe2026.png)

The 5 images are:
![img_0482](https://cloud.githubusercontent.com/assets/12475528/7785974/d00af5d8-0173-11e5-953b-90da75ee8041.JPG)
![img_0483](https://cloud.githubusercontent.com/assets/12475528/7785975/d39e281e-0173-11e5-8b45-0df6c7cffde1.JPG)
![img_0484](https://cloud.githubusercontent.com/assets/12475528/7785976/d66b3eba-0173-11e5-9c7d-0902af797e77.JPG)
![img_0485](https://cloud.githubusercontent.com/assets/12475528/7785977/deeea5cc-0173-11e5-9e9b-d1350fd508a9.JPG)
![img_0486](https://cloud.githubusercontent.com/assets/12475528/7785978/e40afec0-0173-11e5-9bce-8e26912b7776.JPG)

**Comment by paulinus** [comment]
Hi @michaelgli,
the problem on this images is that the mouse is too shiny and has too little texture. SfM is based on detecting and matching feature points between images. For these images, all the points that the matcher can find are on the table, so that is the only points you get.  You can use `bin/plot_matches` to see which points have been matched

![screenshot 2015-06-06 17 09 09](https://cloud.githubusercontent.com/assets/841954/8020157/1d1a550c-0c6f-11e5-9122-89588abf5010.png)

Other than that, the way you took the pictures is fine. You should give it a try with an object with more texture.
