### ISSUE TITLE
Why use the topocentric_from_lla?

### ISSUE THREAD

**Issue by KeoChi** [mapillary/OpenSfM#418]
Hello! I learned about this OpenSfM from [ODM](https://github.com/OpenDroneMap/ODM). In geo.py, is the funtion of topocentric_from_lla to convert the geographic coordinate system to the local coordinate system? What is the purpose of this practice?
   And I have a problem that has been bothering for a long time. I have already asked questions[ in ODM community](https://community.opendronemap.org/t/failed-to-create-orthophoto/2187/5). This problem may be related to OpenSfM. I beg you to be able to check out [this link](https://community.opendronemap.org/t/failed-to-create-orthophoto/2187/5) and be able to answer my questions. Thank you!

**Comment by paulinus** [comment]
Hi @KeoChi, the geometric computations that are done during the reconstruction process need to happen in a Euclidean space. Lat, lon, alt coordinates are not a Euclidean space so we need to convert them.

It is also useful that the coordinates have reasonably small values which make some computation better conditioned.

So we chose to work on a topocentric coordinate system with its origin near the image locations.

About the orientation issue in the ODM forum, the problem is that when images are taken in a straight line, their orientation is undetermined. You can turn any valid reconstruction around the line of the cameras and you will get another valid reconstruction.

You can tell OpenSfM to assume that the cameras are looking down by adding the following options in `config.yaml`
```
align_method: orientation_prior       # orientation_prior or naive
align_orientation_prior: vertical     # horizontal, vertical or no_roll
```
This will choose the reconstruction where the cameras look down which will be closer to reality.

In any case, a better way to solve the ambiguity is by taking images that are not all in a straight line.
