### ISSUE TITLE
Does export_pmvs still work?

### ISSUE THREAD

**Issue by chris-cooper** [mapillary/OpenSfM#44]
Just wondering if export_pmvs is still functioning correctly from the latest master?  Should I expect a reasonable result from the Berlin dataset?  Perhaps this is a question for @ktuite .

I was able to run it but the resulting pointcloud seemed a bit abstract.

**Comment by paulinus** [comment]
I have probably broken it with recent changes. Berlin should work fine. Will look at it

**Comment by ktuite** [comment]
I haven't worked on it in a while so I'm not sure.

**Comment by paulinus** [comment]
I finally took the time to look at it. It was working, but it works better when using smaller images. I've modified the script so that pmvs will use images of the same size as opensfm uses when extracting features.

For Berlin, we only get the closest columns. Datasets with more images of the same object work much better.

Let me know if it works for you, thanks!

**Comment by chris-cooper** [comment]
Thanks @paulinus.  I've done a fresh rebuild and am able to get the columns from Berlin.
