### ISSUE TITLE
Issue with multiple reconstructions for single dataset

### ISSUE THREAD

**Issue by arunmallya** [mapillary/OpenSfM#479]
What does it mean when a dataset produces a list in `reconstruction.json` with length >1?
A list of length 0 (unable to reconstruct) and length 1 (scene was reconstructed) are intuitive.
I was unsure what a length > 1 meant. I obtained a list of length 3 by running the `bin/opensfm_run_all` on the provided `lund` dataset. From looking at the images, there was no large jump in the sequence. Further, there was one point with the same id in 2 of the 3 reconstructions, with same `color` but with different `coordinates`.
E.g.:
```
"304": {
    "color": [
        126.0,
        127.0,
        122.0
    ],
    "coordinates": [
        822314.6654081362,
        5245649.750484779,
        -2870624.023599733
    ]
}
...
"304": {
    "color": [
        126.0,
        127.0,
        122.0
    ],
    "coordinates": [
        822186.3883317207,
        5245728.435108406,
        -2870685.710192186
    ]
},
```
I was under the impression that every unique 3D world point gets a unique id, but this seems to not be the case?
Further, is the reference frame the same for all the reconstructions in `reconstruction.json`?

**Comment by YanNoun** [comment]
Hi,

Sometimes, OpenSfM isn't able to reconstruct a single continuous chunks of cameras. Mostly if there's not enough overlap at some point (the incremental reconstruction can't resect the next shot, and thus start a new reconstruction).

Actually, the `lund` sequence has such weak overlap condition, and sometimes (due to RANSAC + bundle adjustment numerical instability) ends up being broken into 21+9 images reconstructions.

However, since, OpenSfM uses a single track structure (the `construct_tracks` command), both reconstruction might share a few tracks IDs : it also means that both reconstructions could be re-aligned together using 3D<->3D correspondences.

Hope that helps,

Yann

**Comment by arunmallya** [comment]
Thanks for the explanation. I was not expecting that the same id would have different locations, or that different partial reconstructions would have some common ids instead of mutually exclusive.
