### ISSUE TITLE
Projection Bug

### ISSUE THREAD

**Issue by arunmallya** [mapillary/OpenSfM#484]
Note that while projecting 3D points to an image, points behind the camera are not thrown away. This results in incorrect projection outputs.
https://github.com/mapillary/OpenSfM/blob/master/opensfm/types.py#L613-L621

`camera_point = self.pose.transform(point)` converts from world coordinates to camera coordinates. As noted in the docs (https://www.opensfm.org/docs/geometry.html#camera-coordinates), `"A point in front of the camera has positive Z camera coordinate."`  
Projecting points behind the camera wouldn't make much sense, in the general case.
An optional filter, which implements `camera_point = camera_point[camera_point[:, 2] > 0]` would be useful (this only keeps points which are in front of camera, or have positive Z camera coordinate).

**Comment by paulinus** [comment]
Thanks for the suggestion, @arunmallya.  OpenSfM supports multiple camera types. Some of them (`fisheye` and `equirectangular`) do actually see stuff behind the camera. So projecting points with negative Z coordinates is fine there.
Since `shot.project` should work for any camera type, it is not possible to discard points behind the camera in that method.

If you need such a test for a particular application, you can project by doing first a call to `shot.pose.trasform` then doing the check and finally calling `shot.camera.project` and skip the `shot.project` method.
