### ISSUE TITLE
On PositionPriorError

### ISSUE THREAD

**Issue by gaosanyuan** [mapillary/OpenSfM#526]
I have a doubt on PositionPriorError when it comes to compute the residuals.
In my opinion, residuals shoule be -p - position_prior, where is the minus symbol in the original implementation?
Thanks

struct PositionPriorError {
  PositionPriorError(double *position_prior, double std_deviation)
      : position_prior_(position_prior)
      , scale_(1.0 / std_deviation)
  {}

  template <typename T>
  bool operator()(const T* const shot, T* residuals) const {
    T Rt[3] = { -shot[BA_SHOT_RX], -shot[BA_SHOT_RY], -shot[BA_SHOT_RZ] };
    T p[3];
    ceres::AngleAxisRotatePoint(Rt, shot + BA_SHOT_TX, p);

    residuals[0] = T(scale_) * (p[0] + T(position_prior_[0]));
    residuals[1] = T(scale_) * (p[1] + T(position_prior_[1]));
    residuals[2] = T(scale_) * (p[2] + T(position_prior_[2]));
    return true;
  }

  double *position_prior_;
  double scale_;
};

**Comment by gaosanyuan** [comment]
Maybe in ceres, residual equals to ground truth sub prediction,?

**Comment by YanNoun** [comment]
Hi,

It's because we used (but it changed recently) the camera parametrization, where the camera center is expressed as `C = -R(transpose).T` with R and T being the world's origin expressed wrt. to the camera.

We changed it and are now using world parametrization where `C = T`: https://github.com/mapillary/OpenSfM/pull/546/files

Let me know if that helps.

Yann

**Comment by YanNoun** [comment]
No answer in a while, closing.
