### ISSUE TITLE
setting higher feature_process_size gives less dense point cloud

### ISSUE THREAD

**Issue by dicobrazz** [mapillary/OpenSfM#550]
Hi,

When increasing feature_process_size or setting it to -1 to use original size the resulting point cloud has less point (less dense) than when using the default value for feature_process_size.

Is that normal? Should other settings change as well to match the image size and produce denser point cloud?

Regards

**Comment by YanNoun** [comment]
Hi,

Yes, it is not expected. Larger image should results in more keypoints. Could you share just one image of your dataset, so I can have a look and try.

Thank you,

Yann

**Comment by dicobrazz** [comment]
> Hi,
> 
> Yes, it is not expected. Larger image should results in more keypoints, in the sparse reconstruction (`reconstruction.json`). For the dense point cloud (`ply` file), it is controlled by `depthmap_resolution`. Could you share 3 images of your dataset, so I can have a look and try.
> 
> Thank you,
> 
> Yann

Hi Yann,

Here is a dropbox link, where you can download:
https://www.dropbox.com/sh/k89t33om1hy30pv/AADtQ1J2ZVq8RdsofY_LjtSJa?dl=1

**Comment by paulinus** [comment]
The number of feature points extracted on each image is controlled by the `feature_min_frames`. So even with larger images, the number of extracted features should be similar.

There is an additional phenomenon that happens when images are larger. It becomes more likely that a point detected in one image is not detected in another image. This can result in a reduced number of reconstructed points.

So if you want more precision, make images larger and, at the same time, increase `feature_min_frames`.

**Comment by YanNoun** [comment]
No answer in a while, closing.
