### ISSUE TITLE
How to set a random seed?

### ISSUE THREAD

**Issue by EchoTHChen** [mapillary/OpenSfM#566]
I find that the reconstruction results, such as _depthmap/merged.ply and reconstruction.json_, are not the same for the same images. What can I do to get the same reconstruction results for the same images?

**Comment by paulinus** [comment]
We have currently no way of ensuring identical results for multiple runs.

There are two sources of randomness. Firstly, there is a number of places where random numbers are used. Most notably, during the RANSAC and PatchMatch algorithms. As of now, there is no exposed way of setting an initial seed for this.

Secondly, some algorithms sort data based on memory positions (Ceres does this internally IRC). Since memory positions are different between executions, it is difficult to ensure identical results.

**Comment by EchoTHChen** [comment]
Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pau Gargallo"<notifications@github.com&gt;; 
发送时间: 2020年3月30日(星期一) 晚上11:44
收件人: "mapillary/OpenSfM"<OpenSfM@noreply.github.com&gt;; 
抄送: "3296271079"<3296271079@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mapillary/OpenSfM] How to set a random seed? (#566)





 
We have currently no way of ensuring identical results for multiple runs.
 
There are two sources of randomness. Firstly, there is a number of places where random numbers are used. Most notably, during the RANSAC and PatchMatch algorithms. As of now, there is no exposed way of setting an initial seed for this.
 
Secondly, some algorithms sort data based on memory positions (Ceres does this internally IRC). Since memory positions are different between executions, it is difficult to ensure identical results.

**Comment by YanNoun** [comment]
No answer in a while, closing.

**Comment by LukasBommes** [comment]
Would not it not be very helpful for testing if there was no randomness in the results for the same dataset? I see that some tests check whether values lie within certain ranges. Would it not be better if you could test against concrete values?
