### ISSUE TITLE
While undistorting  maximum 15 images are used. Any specific reason for that?

### ISSUE THREAD

**Issue by vinayver198** [mapillary/OpenSfM#579]
Hi,
I have got around 1500 images, but when I am running undistort only 15 images are used . I repeated same for other set of data, same thing happened. Is there any specific reason to use only 15 images ?

**Comment by paulinus** [comment]
Undistortion should undistort all reconstructed images. Did all the 1500 images get reconstructed?

**Comment by vinayver198** [comment]
I am having 15 images in my reconstruction.json. I guess that's the reason behind having only 15 images while undistorting. Can you let me know how can I increase the images used in recontruction process.

**Comment by paulinus** [comment]
OpenSfM will try to reconstruct all of the images. However, it may fail to reconstruct some. Usually, this happens when the overlap between the images is not large enough. SfM needs to see each part of the scene in at least 3 images, ideally more.
Another source of errors is not having a decent initial camera calibration.

**Comment by vinayver198** [comment]
When we run undistorted, it gives reference images from index=0(by default) from reconstruction.json. Can we grow the reconstruction to further more or any possiblity to compute depthmaps for every index and then combine the depthmaps in order to compute pointcloud for large set of images?

**Comment by vinayver198** [comment]
Issue resolved.
