### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by nav74neet** [mapillary/OpenSfM#683]
Hey @paulinus, im trying to generate a reconstruction for a bunch images, but unfortunately facing the facing the following error:

------------------
root@36e518c38a9b:/source/OpenSfM# bin/opensfm extract_metadata data/imow
Traceback (most recent call last):
  File "/source/OpenSfM/bin/opensfm_main.py", line 15, in <module>
    commands.command_runner(commands.opensfm_commands, default_dataset_type)
  File "/source/OpenSfM/opensfm/commands/command_runner.py", line 31, in command_runner
    command.run(data, args)
  File "/source/OpenSfM/opensfm/commands/command.py", line 12, in run
    self.run_impl(data, args)
  File "/source/OpenSfM/opensfm/commands/extract_metadata.py", line 11, in run_impl
    extract_metadata.run_dataset(dataset)
  File "/source/OpenSfM/opensfm/actions/extract_metadata.py", line 49, in run_dataset
    data.save_camera_models(camera_models)
  File "/source/OpenSfM/opensfm/dataset.py", line 495, in save_camera_models
    with io.open_wt(self._camera_models_file()) as fout:
  File "/source/OpenSfM/opensfm/io.py", line 649, in open_wt
    return open(path, "w", encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'data/imow/camera_models.json'
------------------

I have attached images, that i will be using: https://drive.google.com/drive/folders/1zzT_n6DrtlOaHjsru03QoeUngTfuA7sS?usp=sharing

**Comment by fabianschenk** [comment]
Hi @nav74neet,
Thanks for trying OpenSfM :) I'm not Paulinus but I can also help you.
I see a few problems with how you install/run OpenSfM but I'll discuss this later.
The short answer to your problem is that the folder `data/imow` doesn't exist.
Make sure that the path exists, e.g. `ls /source/OpenSfM/data/imow`. The folder `/source/OpenSfM/data/imow` should contain all the images in a folder called `images`.
If the path exists and you put the images into the correct folder (`/source/OpenSfM/data/imow/images`), try with the absolute path
```
bin/opensfm extract_metadata /source/OpenSfM/data/imow
```
Now I'd like to point out a few issues that I see with how you run OpenSfM:
- You shouldn't run OpenSfM (or nearly all other stuff) from a `root` shell since you might run into all kinds of trouble, e.g. files not accessible by a normal user, ... OpenSfM runs perfectly fine as normal user.
- It also seems like you have it installed in `/source/OpenSfM`, whereas it would be better to put it into your home directory. Probably something like `/home/USERNAME/OpenSfM` and run it from there.

I also looked at the images and 3D reconstruction might not work as you expect. You might need images from different angles or with a wider field of view.
