### ISSUE TITLE
NO_CONVERGENCE

### ISSUE THREAD

**Issue by ananthsethuraman** [mapillary/OpenSfM#684]
I submitted a set of five images, and ran them just like the Berlin test case. I got the error message NO_CONVERGENCE.

Because the pictures are personal, I do not want to share them in a public site. If Mapillary can provide me a private spot where I can upload or email the five images, that would be great.

Thanks.

**Comment by fabianschenk** [comment]
@ananthsethuraman  Could you please share the output log including the number of detected and matched keypoints and also the optimization steps?
Most of the time the logs are enough to figure out what's going wrong.

**Comment by ananthsethuraman** [comment]
Hi Fabian,

Thanks for offering to look at the matter. I've attached two log files: profile.log and ananth.log.

profile.log got generated automatically.

ananth.log got generated because I typed this on the command line:
                  bin/run_all    data/ananth    |&    tee    ananth.log

Thanks once again.


[profile.log](https://github.com/mapillary/OpenSfM/files/5698154/profile.log)
[ananth.log](https://github.com/mapillary/OpenSfM/files/5698155/ananth.log)

**Comment by fabianschenk** [comment]
Hi @ananthsethuraman,
Thanks for attaching the logs. I don't check the Issues regularly and mostly react on pings `@`.
I think you get `NO_CONVERGENCE` since the optimizer just stops after 50 iterations.
From what I can see from the logs, you have very few matches, inliers and triangulated points. Do you have a very wide baseline? I would try to take more images, e.g. walk slowly and take a picture every second. Make sure that you have patterns or textures in there that work well for matching and avoid grass and repetitive structures. Take a look at the `lund` and `berlin` example datasets to get an idea. For a quick test, you could also take pictures in the living room and try to run with those images.

**Comment by ananthsethuraman** [comment]
Hi Fabian,

The words "I would try to take more images," were most helpful. I snapped 30 images, ran Mapillary on those 30 images and got a good 3D reconstruction immediately. It was not a fluke, for I tried again with 39 images and yet again with 25 images.

Thanks once again.

Happy New Year greetings in advance.
