### ISSUE TITLE
Bad projection from 3D points to image

### ISSUE THREAD

**Issue by Juliocasta5** [mapillary/OpenSfM#701]
Hi guys,

I'm doing my final degree master project using OpenSfm. After doing the reconstruction, I want to project the pointcloud to the image. So, I get the camera pose from the image and convert it into a 4x4 matrix with translation and rotation. Afterthat, I am multplying the whole pointcloud by the matrix and, then, when I have the pointcloud in the camera coordenates, I project the pointcloud to the image using pinhole. The thing is I am projecting the pointcloud but it doesn't fit the whole image. This is the result.
![Captura de pantalla de 2021-01-29 12-40-07](https://user-images.githubusercontent.com/62712059/106271021-25143b80-622f-11eb-8991-9db628f686ad.png)

The reconstruction was done with perspective camera, son i've tried to use the project function of OpenSfm but it doesn't work. I've have also tried to to the reconstruction with fisheye camera and use the project function, but it doesn't work either. If you guys could help me to find the right projection.

I attach the code, the image, the pointcloud, the reconstruction.json file.

Thanks in advance.
[opensfm.zip](https://github.com/mapillary/OpenSfM/files/5893604/opensfm.zip)

**Comment by fabianschenk** [comment]
Hi @Juliocasta5 ,
thanks for trying OpenSfM and for sharing some data to work with.
I think your mistake with the OpenSfM `project` function was that you didn't convert the normalized coordinates back to pixel coordinates.

I've written a short example to project the points in `reconstruction.json` and the points in the PCL to the image.
`reconstruction.json` only has around 2k points but the PCL has around 20k. How did you create the PCL? 
When projecting, it is slightly off, which could be because of wrong distortion parameters.

Here are the two images:
![img2_rec](https://user-images.githubusercontent.com/13796836/106279024-11bb9d00-623c-11eb-8dee-fb0025509975.jpg)
![img3_pcl](https://user-images.githubusercontent.com/13796836/106279027-13856080-623c-11eb-917c-debed5f8d313.jpg)

Here's the script I used:
[test_reproject.py.txt](https://github.com/mapillary/OpenSfM/files/5893997/test_reproject.py.txt)

**Comment by Juliocasta5** [comment]
Hello Fabian,
First of all, I want to thank you for helping me with this issue.

When you mention PCL, do you mean the ply pointcloud? This is the pointcloud I get from the Opensfm reconstruction. After the reconstruction, you can find It inside the file of your data, OpenSfm/data/yourreconstructionfile/undistorted/depthmaps.

So, It means that OpenSfm uses another origin of coordenates? Thank you very much.

**Comment by Juliocasta5** [comment]
Hi @fabianschenk,
I'm trying to use your script but i'm getting the following error:

AttributeError: 'opensfm.pygeometry.Camera' object has no attribute 'normalized_to_pixel_coordinates'

I can't find the function normalized_to_pixel_coordinates. If you could tell me where it is.

Thank you.

**Comment by fabianschenk** [comment]
Hi @Juliocasta5 ,
> Hello @fabianschenk ,
> First of all, I want to thank you for helping me with this issue.
> 
> When you mention PCL, do you mean the ply pointcloud? This is the pointcloud I get from the Opensfm reconstruction. After the reconstruction, you can find It inside the file of your data, OpenSfm/data/yourreconstructionfile/undistorted/depthmaps.
> 
> So, It means that OpenSfm uses another origin of coordenates? Thank you very much.

I've tried with `berlin` and there it looks correct, so I assume that the script works. Maybe the estimated camera parameters are not ideal. You could try to write the cameras with the estimated calibration into the `camera_model_overrides.json` and run the whole pipeline again with to refine the calibration parameters.

![img3](https://user-images.githubusercontent.com/13796836/106296623-3589dd80-6252-11eb-92b1-e9e058b09fd3.jpg)


> Hi @fabianschenk,
> I'm trying to use your script but i'm getting the following error:
> 
> AttributeError: 'opensfm.pygeometry.Camera' object has no attribute 'normalized_to_pixel_coordinates'
> 
> I can't find the function normalized_to_pixel_coordinates. If you could tell me where it is.
> 
> Thank you.

Please, make sure that you are running the most recent version. `normalized_to_pixel_coordinates` is defined in [pybind.cc](https://github.com/mapillary/OpenSfM/blob/master/opensfm/src/geometry/python/pybind.cc)

**Comment by Juliocasta5** [comment]
I think I'm not using the last version but I found a similar function and the operation to transform the coordenates into pixels. Finally, everything is working well and I achieved my goal.

Before closing the issue, I wonder if you @fabianschenk could explain me what the transformation from these coords to pixels means. I don't understand well how OpenSfm works with this kind of coordenates.

Thank you very much, you've helped me a lot.

**Comment by fabianschenk** [comment]
Hi @Juliocasta5 ,

The transformation from the global position (`pt3D`) to the local `frame` works as it normally would with `R` being the rotation and `t` being the translation.
Then you project by multiplying the rotated 3D pt onto the intrinsic camera matrix `K` and convert to `x` and `y` like you normally would: 
```
pt2D_frame = K * (R * pt3D + t)
z = pt2D_frame[2]
x = pt2D_frame[0]/z
y = pt2D_frame[1]/z
```
However, `x` and `y` are now in normalized coordinates (see [doc](https://www.opensfm.org/docs/geometry.html)).
This is because we use a normalized version of the intrinsic camera matrix `K`, where e.g. `focal x` is divided by `max(width, height)`. This version is not used often in the literature but offers some benefits when optimizing. That's why you have to perform an additional denormalization step to compute the pixel coordinates.
You can retrieve a different `K` to project directly to pixel coordinates by calling [`GetProjectionMatrixScaled`](https://github.com/mapillary/OpenSfM/blob/3f6a3d95908f09e9b3e7a21b9f75fda1d01972c4/opensfm/src/geometry/src/camera.cc#L243) .

I hope this helps, 
Fabian

**Comment by Juliocasta5** [comment]
Ok, now I understand why it's important this transformation. Thank you @fabianschenk for helping me, I really appreciate your efforts. I'm closing the issue now, but maybe I will post something else if I get stuck again.
Thanks!
