### ISSUE TITLE
executing python code directly

### ISSUE THREAD

**Issue by monschine** [mapillary/OpenSfM#776]
Hi, 

I have a manual system for inputting control points between images and creating the matching pairs.
Is it possible to execute directly python code without building the whole library.
I'm actually interested only in the tracking part, so I have the feature matches and would like to find camera pose, not even making reconstruction , ...

Any advice or tip would be most welcome

Thanks in advance

**Comment by fabianschenk** [comment]
Hi @monschine ,

Thanks for using OpenSfM. Since most of our heavy-computation code is in C++, you will probably not get around building the whole library. However, this takes only 2-5 mins if you have all the dependencies installed, so I don't really see the problem there.
Afterwards you can just import any OpenSfM libraries into your code.

Good luck,
Fabian

**Comment by monschine** [comment]
Hi @fabianschenk, 

thanks for your quick answer. For architectural purpose I would like to use just python, and I guess the process I'm interested in, camera pose estimation based on the manual feature match, is not that computation heavy. So I would like to know if it would be still possible to run the python code.

Thanks again

**Comment by fabianschenk** [comment]
Hi @monschine ,

we include many C++ libraries with Python bindings, e.g. `pymap`, `pygeometry`,... , so you can't just run the code without them. Maybe you can find some inspiration in our codebase to build your own algorithm.
Good luck

**Comment by monschine** [comment]
thanks, I already moved into that direction
