### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by haby0** [mapillary/OpenSfM#810]
What would be the right contact to report a security vulnerabilty? thanks!

**Comment by haby0** [comment]
One month has passed since the last communication, do you have any news to reply to me?

**Comment by fabianschenk** [comment]
Hi @haby0 ,

Thanks again for reporting this issue.
As I said in the mail, I forwarded this to the responsible developer and created a task. 
Please note that the SfM Viewer is a pure local development tool and should NOT run in a production setting, where anybody other than you can accesses the server! With this in mind, we don't consider the "vulnerability" critical, thus it's not really high up in our list of tasks.

Since this is an open source project, there's always the possibility to create a PR that fixes the vulnerability. Feel free to go this way and link to this issue :D

Thanks again and looking forward to your contribution. 

Best,
Fabian
