### ISSUE TITLE
Combine multiple partial reconstructions into single reconstruction.

### ISSUE THREAD

**Issue by QuickLearner171998** [mapillary/OpenSfM#835]
Hi,

I am using OpenSFM codebase on my personal dataset. I am getting multiple partial reconstructions 

![image](https://user-images.githubusercontent.com/31489611/146444107-91df4c29-6a7b-4271-8ada-6764d00393c4.png)

I want to combine all the reconstructions into a single reconstruction. I have written a small piece code also for the same -

```python

        r_ini = reconstructions[reconstruction_index]
        for r in reconstructions[1:]:
            for shot in r.shots:
                if shot not in r_ini.get_shots():
                    r_ini.add_shot(r.get_shot(shot))
            for point in r.points:
                if point not in r_ini.get_points():
                    r_ini.add_point(r.get_point(point))
```

But this gives incorrect reconstructions. (Which I checked by visualizing final  `merged.ply` file.

**Can you please help with the correct way of combining the partial reconstructions into one single reconstruction?**

Thanks

**Comment by fabianschenk** [comment]
Hi @QuickLearner171998 ,

Great that you're using OpenSfM.

You're actually quite close to the solution.

Could you try the following "untested" code:
```
from opensfm import io, types
import json

output = types.Reconstruction()
if len(recs) > 0:
     output.reference = recs[0].reference
for rec in recs:
    for camera in rec.cameras.values():
        output.add_camera(camera)
    for shot in rec.shots.values():
        output.add_shot(shot)
    for point in rec.points.values():
        newp = output.create_point(str(num_tracks))
        newp.coordinates = point.coordinates
        newp.color = point.color
        num_tracks += 1

with open("reconstruction_merged.json","w") as fp:
   json.dump(io.reconstructions_to_json([output],fp)
```

**Comment by QuickLearner171998** [comment]
Hi @fabianschenk, thanks for the reply.
The above code works fine and a single `reconstruction.json` file is generated. However, the visualization doesn't seem correct. Can it be due to each partial reconstruction having a different coordinate frame? 

Can you please guide me on how I can create correct 3D points from the multiple partial reconstructions?

Thank You!

**Comment by fabianschenk** [comment]
Hi @QuickLearner171998 ,

I didn't think this fully through :D If you have partial reconstructions then there were not enough correspondences between the images, so they were split into several reconstructions. 
Transforming them somehow to a common coordinate system typically does not work because also the 3D points and poses of some of the smaller reconstructions can be wrong.
Your first and second reconstruction with 28 images and 16 images are probably good but the rest probably doesn't look to great.

A good way to address this problem is by recording more images to guarantee an overlap. Try to avoid sky and moving objects (cars, pedestrians) in the recording.
You can also try to modify the matching parameters in the `config.yaml`, e.g. reducing the number of required inliers,..

Good luck,
Fabian

**Comment by fabianschenk** [comment]
No response in 2 weeks, so I guess the issue has been resolved. Reopen if needed.
