### ISSUE TITLE
pygeometry, pymap files missing

### ISSUE THREAD

**Issue by JKViswanadham14** [mapillary/OpenSfM#917]
I cannot find the files pygeometry, pymap e.t.c in opensfm folder. can some one please help?

**Comment by fabianschenk** [comment]
Hi @JKViswanadham14 ,

You'll not find it because it doesn't really exist as a file. `pygeometry`, `pymap`, etc. are Python bindings for C++libraries and the `pyXXX` libraries are built when you compile OpenSfM.
The definition of `pygeometry` is here: https://github.com/mapillary/OpenSfM/blob/21e998876f637920ebdaf92030f5d8b0d761fdf1/opensfm/src/geometry/python/pybind.cc#L14

You'll find all the other definitions `pyXXX` in the `pybind.cc` files in the respective folders.

For each Python library, there's also a `*.pyi` file, which defines the Python interface so that an IDE can run code completetion, etc.
For example: [pygeometry.pyi](https://github.com/mapillary/OpenSfM/blob/main/opensfm/src/geometry/pygeometry.pyi)

Best,
Fabian
